### ISSUE TITLE
Add reusable script parsing code to separate folder

### ISSUE THREAD

**Issue by trbKnl** [d3i-infra/data-donation-task#17]
# Code to add 

* Helpers + unzipddp
 - port helpers
 - extraction helpers (include exceptions in that file)
* Validation code

**Comment by Anju023** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
