### ISSUE TITLE
Large donations throw a MemmoryError

### ISSUE THREAD

**Issue by trbKnl** [d3i-infra/data-donation-task#24]
# Large donations throw a MemmoryError

When a very large string > (300MiB of donated data) gets sends back to pyodide. The code throws a memory error or grinds to a halt. 

The copying of objects from javascript to pyodide and vice versa seems to work fine up to a point, but it cant handle 300MiB. If you inspect memory usage in the browser its over 2GiB. The point where wasm should stop working and throw an error.

Tried to look for memmory leaks, I dont think there are any. Could not find any obvious mistakes.

There is probably a way around this. 

But another solution might be better avoid the round trip to pyodide altogether, how it works now is as follows:

```
1. extraction
2. data to consent form, consent yes
3. data from consent form back to pyodide
4. call to `donate()` again back to the main threat
5. to bridge
```

Step 3 and 4 are unnecessary. I propose:

```
1. extraction
2. data to consent form, consent yes
3. data from consent form to bridge
```

This makes more sense. Requires:

* new payload type that can be set configured in the consent form table as resolve type
* intercept in worker_engine.ts
* if its a donation pass donate command back to command handler
* resolve with a donation success message
* slight change to `script.py`  ConsentForm should accept filename or key parameter so you can influence the filename

**Comment by mellelieuwes** [comment]
Looks good to me @trbKnl . One question: how is the use case handled when participant deleted some rows on the consent page?

**Comment by trbKnl** [comment]
Still work the same as before!
